{"name": "test_del[info0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 == 1\n +  where 0 = <bound method delete_meal.asse of <business.delete_setmeal.delete_meal object at 0x000001D2B855D748>>()\n +    where <bound method delete_meal.asse of <business.delete_setmeal.delete_meal object at 0x000001D2B855D748>> = <business.delete_setmeal.delete_meal object at 0x000001D2B855D748>.asse", "trace": "info = [1]\n\n    @pytest.mark.parametrize('info',l)\n    \n    def test_del(info):\n        d=delete_meal('ff')\n        d.dele()\n>       assert d.asse()==1\nE       assert 0 == 1\nE        +  where 0 = <bound method delete_meal.asse of <business.delete_setmeal.delete_meal object at 0x000001D2B855D748>>()\nE        +    where <bound method delete_meal.asse of <business.delete_setmeal.delete_meal object at 0x000001D2B855D748>> = <business.delete_setmeal.delete_meal object at 0x000001D2B855D748>.asse\n\ncase\\test_dele.py:17: AssertionError"}, "parameters": [{"name": "info", "value": "[1]"}], "start": 1616467465996, "stop": 1616467468001, "uuid": "e9e0c189-6d78-44bf-b7e5-59db84660551", "historyId": "9ba74c5782cd4206fccedf1ed1b116ae", "testCaseId": "da973dc745e735f3b37730883fa4b67a", "fullName": "case.test_dele#test_del", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_dele"}, {"name": "host", "value": "LAPTOP-U1PCAPFC"}, {"name": "thread", "value": "11736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_dele"}]}